# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_cor <- function(mat) {
    .Call(`_clhs_c_cor`, mat)
}

table_cpp <- function(v, full) {
    .Call(`_clhs_table_cpp`, v, full)
}

CppLHS <- function(xA, cost, strata, include, factors, i_fact, nsample, cost_mode, iter, wCont, wFact, wCorr, temperature = 1, tdecrease = 0.95, length_cycle = 8L) {
    .Call(`_clhs_CppLHS`, xA, cost, strata, include, factors, i_fact, nsample, cost_mode, iter, wCont, wFact, wCorr, temperature, tdecrease, length_cycle)
}

rcpparma_hello_world <- function() {
    .Call(`_clhs_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_clhs_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_clhs_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_clhs_rcpparma_bothproducts`, x)
}

