# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CppLHS <- function(xA, cost, strata, include, factors, i_fact, nsample, cost_mode, iter, wCont, wFact, wCorr, temperature = 1, tdecrease = 0.95, length_cycle = 8L) {
    .Call(`_clhs_CppLHS`, xA, cost, strata, include, factors, i_fact, nsample, cost_mode, iter, wCont, wFact, wCorr, temperature, tdecrease, length_cycle)
}

